[package]
name = "rdserver"
version = "0.1.0"
authors = ["may"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
futures = "0.3"
bytes = "0.4.12"